name: Issues monitoring notifier
on:
  issues:
    types: [opened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: New issue created
        run: echo "${{ toJSON(github.event) }}" # outputting trigger event related information